### ISSUE TITLE
If client has unsupported language then webUI hangs on loading spinner

### ISSUE THREAD

**Issue by jimlei** [airdcpp-web/airdcpp-webui#7]
Open the webUI with an invalid language. Either use an unsupported language or change i18nextLng in local storage to ie `nb-NO` (norwegian)

This throws a js error in the console and the webUI never loads.

```
Error: Cannot find module './nb/webui.main.json' .*$:32
    r .*$:32
    o .*$:27
    ajax LocalizationService.ts:22
    value index.js:82
    value index.js:75
    value BackendConnector.js:160
    value BackendConnector.js:226
    value BackendConnector.js:199
    forEach (index):262
    value BackendConnector.js:198
    value BackendConnector.js:205
    value i18next.js:210
    o i18next.js:290
    value i18next.js:296
    s i18next.js:149
i18next::backendConnector: loaded namespace main for language en
```

Since this blocks the webUI completely I think it should be changed so the fallback language is used both when the service can not detect the language but also if it is an unsupported language.

Also since you are familiar with the translation here. Norwegian identifies with no and nb, or even nn for another variant of the language which one may want to use at least until both translation variants exist. Should this be reported here, in i18next-browser-languagedetector or somewhere else?

**Comment by maksis** [comment]
> I think it should be changed so the fallback language is used both when the service can not detect the language but also if it is an unsupported language.

Indeed. It failed at the `require` function, which wasn't handled at all and the fallback locale was never loaded. This will be fixed in the next version.

> Norwegian identifies with no and nb, or even nn for another variant of the language which one may want to use at least until both translation variants exist. Should this be reported here, in i18next-browser-languagedetector or somewhere else?

This seems to be related to naming of the resource files in this project. The [language at Transifex is currently `Norwegian (Norway)`](https://www.transifex.com/airdcpp/airdcpp/language/no_NO/) (locale `no_NO`), so in that sense the resource name `no` is correct. `Norwegian Bokmål (Norway)` might have been a better language to use, but as I highly doubt that other Norwegian language variants will be added in this project (even the current Norwegian translation is missing almost half of the strings), so I'm not sure if changes are necessary.

The language chosen by `i18next-browser-languagedetector` is generally being used only before logging in. When the user logs in, the UI language is being synced with the application language, after which the proper resource file should be loaded.
